//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo10.Order
{
    using System;
    using System.Collections.Generic;
    
    public partial class datum
    {
        public int id { get; set; }
        public string ten { get; set; }
        public string lienlac { get; set; }
        public string mota { get; set; }
        public Nullable<System.DateTime> ord { get; set; }
        public Nullable<System.DateTime> giao { get; set; }
        public byte[] img { get; set; }
        public string tong { get; set; }
        public string coc { get; set; }
        public string path { get; set; }
    }
}
